window.EVENT_DATA = {
  demoTime: "13:52",
  games: [
    { id: "gather", title: "참가자 집합", start: "09:00", end: "09:30", location: "다목적 구장", sport: "행사", kind: "support", summary: "오전 경기 참가자 집합 및 안내" },
    { id: "warmup", title: "몸풀기", start: "09:30", end: "09:40", location: "다목적 구장", sport: "행사", kind: "support", summary: "본게임 시작 전 전체 몸풀기" },
    { id: "futsal-qual-1", title: "풋살 예선 1", start: "09:40", end: "10:15", location: "다목적 구장", sport: "풋살", kind: "game", mapKey: "multipurpose", summary: "24학번 vs 26학번" },
    { id: "basketball-qual-1", title: "농구 예선 1", start: "09:40", end: "10:15", location: "다목적 구장", sport: "농구", kind: "game", mapKey: "multipurpose", summary: "23학번 vs 25학번" },
    { id: "futsal-qual-2", title: "풋살 예선 2", start: "10:15", end: "10:50", location: "다목적 구장", sport: "풋살", kind: "game", mapKey: "multipurpose", summary: "22학번 vs 23학번" },
    { id: "basketball-qual-2", title: "농구 예선 2", start: "10:15", end: "10:50", location: "다목적 구장", sport: "농구", kind: "game", mapKey: "multipurpose", summary: "22학번 vs 26학번" },
    { id: "basketball-semi", title: "농구 부결승", start: "10:50", end: "11:25", location: "다목적 구장", sport: "농구", kind: "game", mapKey: "multipurpose", summary: "weaker winner vs 24학번", dependency: "예선 1, 2 결과 필요" },
    { id: "futsal-semi", title: "풋살 부결승", start: "11:25", end: "12:00", location: "다목적 구장", sport: "풋살", kind: "game", mapKey: "multipurpose", summary: "weaker winner vs 25학번", dependency: "예선 1, 2 결과 필요" },
    { id: "lunch", title: "점심시간", start: "12:00", end: "13:00", location: "전체", sport: "행사", kind: "support", summary: "오후 1시 출석체크" },
    { id: "opening", title: "개회사 및 체조", start: "13:00", end: "13:20", location: "대운동장", sport: "행사", kind: "support", summary: "오후 일정 시작" },
    { id: "rope-qual-1", title: "줄다리기 예선 1", start: "13:20", end: "13:35", location: "대운동장", sport: "줄다리기", kind: "game", mapKey: "stadium", summary: "25학번 vs 26학번" },
    { id: "rope-qual-2", title: "줄다리기 예선 2", start: "13:20", end: "13:35", location: "대운동장", sport: "줄다리기", kind: "game", mapKey: "stadium", summary: "22학번 vs 24학번" },
    { id: "rope-semi", title: "줄다리기 부결승", start: "13:35", end: "13:50", location: "대운동장", sport: "줄다리기", kind: "game", mapKey: "stadium", summary: "weaker winner vs 23학번", dependency: "예선 1, 2 결과 필요" },
    { id: "rope-final", title: "줄다리기 결승", start: "13:50", end: "14:05", location: "대운동장", sport: "줄다리기", kind: "game", mapKey: "stadium", summary: "better winner vs 부결승 승자", dependency: "예선 비교 + 부결승 결과 필요" },
    { id: "women-dodgeball-qual-1", title: "여자 피구 예선 1", start: "14:05", end: "14:40", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "23학번 vs 24학번" },
    { id: "women-dodgeball-qual-2", title: "여자 피구 예선 2", start: "14:05", end: "14:40", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "22학번 vs 25학번" },
    { id: "men-dodgeball-qual-1", title: "남자 피구 예선 1", start: "14:05", end: "14:40", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "24학번 vs 26학번" },
    { id: "men-dodgeball-qual-2", title: "남자 피구 예선 2", start: "14:05", end: "14:40", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "23학번 vs 25학번" },
    { id: "women-dodgeball-semi", title: "여자 피구 부결승", start: "14:40", end: "15:15", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "weaker winner vs 26학번", dependency: "자동 배치 예정" },
    { id: "men-dodgeball-semi", title: "남자 피구 부결승", start: "14:40", end: "15:15", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "weaker winner vs 22학번", dependency: "자동 배치 예정" },
    { id: "move-1", title: "이동시간", start: "15:15", end: "15:20", location: "전체", sport: "행사", kind: "support", summary: "다목적 구장으로 이동" },
    { id: "futsal-final", title: "풋살 결승", start: "15:20", end: "15:55", location: "다목적 구장", sport: "풋살", kind: "game", mapKey: "multipurpose", summary: "better winner vs 부결승 승자", dependency: "예선 비교 + 부결승 결과 필요" },
    { id: "basketball-final", title: "농구 결승", start: "15:20", end: "15:55", location: "다목적 구장", sport: "농구", kind: "game", mapKey: "multipurpose", summary: "better winner vs 부결승 승자", dependency: "예선 비교 + 부결승 결과 필요" },
    { id: "move-2", title: "이동시간", start: "15:55", end: "16:00", location: "전체", sport: "행사", kind: "support", summary: "대운동장으로 이동" },
    { id: "women-dodgeball-final", title: "여자 피구 결승", start: "16:00", end: "16:35", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "better winner vs 부결승 승자", dependency: "피구 자동 로직 추후 연결" },
    { id: "men-dodgeball-final", title: "남자 피구 결승", start: "16:00", end: "16:35", location: "대운동장", sport: "피구", kind: "game", mapKey: "dodgeball", summary: "better winner vs 부결승 승자", dependency: "피구 자동 로직 추후 연결" },
    { id: "relay", title: "계주", start: "16:35", end: "16:55", location: "대운동장", sport: "계주", kind: "game", mapKey: "relay", summary: "전체 학번 동시 경기 · game_rankings 사용" },
    { id: "awards", title: "시상식 및 출석체크", start: "16:55", end: "17:10", location: "대운동장", sport: "행사", kind: "support", summary: "최종 시상과 마무리" },
  ],
  booths: [
    { id: "water", name: "물놀이존", location: "청룡관 본부석 옆", start: "13:20", end: "16:35", summary: "체육대회 열기를 식혀줄 시원한 물총 싸움 타임!", guide: "💦 시원하게 한 판! 물놀이 타임\n체육대회 당일, 열기를 식혀줄 시원한 물총 싸움이 가능합니다! 🔫\n• 학생회에서도 물총을 일부 구비해 두었으나, 수량이 넉넉하지 않아요! 😢\n• 제대로 즐기고 싶은 학우분들은 개인 물총을 지참해 주시는 센스! 부탁드립니다. 🌊\n뜨거운 열정과 즐거움이 가득할 이번 체육대회, 우리 모두 다치지 말고 신나게 즐겨봐요! 여러분의 많은 참여 부탁드립니다! 💙", mapCaption: "청룡관 본부석 옆에서 물총을 대여하고 대운동장 쪽으로 이동합니다." },
    { id: "face", name: "페이스 페인팅", location: "대운동장 하단 부스존", start: "13:20", end: "16:35", summary: "페이스페인팅 받고 인증샷 올리면 배민/스타벅스 경품 추첨!", guide: "📸 [SNS Event] 인증샷 찍고 팔로우!\n아름다운 페이스페인팅 받고 추억도 남기세요! 🎨\n• 방법: 페이스페인팅 후 체육대회 인증샷 찰칵! 📸 -> 혜윰 인스타 팔로우 + 태그해서 스토리 업로드!\n• 경품: 추첨을 통해 배민 상품권 3만원(5명) & 스타벅스 1만원(10명) ☕️", mapCaption: "대운동장 하단 부스 구역 가운데쪽입니다." },
    { id: "chase", name: "경찰과 도둑", location: "축구장 중앙 구역", start: "13:20", end: "16:35", summary: "축구장 안쪽에서 진행되는 추격전 게임", guide: "사전 예약자 우선, 빈 타임은 현장 참여 가능합니다.", currentSession: "3타임 · 15:25 - 15:45", mapCaption: "축구장 중앙 검정 테두리 구역에서 진행합니다." },
    { id: "weight", name: "웨이트 챌린지", location: "대운동장 하단 부스존", start: "13:20", end: "16:35", summary: "남자 100kg / 여자 60kg 성공 시 하리보, 남녀 랭킹 1~3위에게 배민 상품권!", guide: "🏋️ 웨이트 챌린지 (The Iron Will)\n• 성공 기준: 남자 100kg / 여자 60kg 성공 시 하리보 젤리 증정!\n• 랭킹 이벤트: 남/여 각 기록 1~3위에게는 배민 상품권 3만원권을 드립니다! (총 6명)\n• 남녀 랭킹 1~3위가 속한 학번에게는 체육대회 전체 점수도 부여!", leaderboard: [{ name: "김민수", team: "24학번", record: "125kg" }, { name: "이서연", team: "22학번", record: "105kg" }, { name: "박서준", team: "25학번", record: "100kg" }], mapCaption: "대운동장 하단 부스 구역 왼쪽에서 운영합니다." },
    { id: "shoe", name: "신발 던지기", location: "대운동장 하단 부스존", start: "13:20", end: "16:35", summary: "30점 이상이면 하리보, 만점자 중 추첨으로 스타벅스 상품권!", guide: "👟 신발 던지기\n• 성공 기준: 과녁에 신발을 던져 30점 이상 획득 시 하리보 젤리 증정!\n• 랭킹 이벤트: 만점자 중 추첨을 통해 스타벅스 상품권 1만원권을 드립니다! (총 10명)", teamTotals: [{ team: "22학번", score: 120 }, { team: "24학번", score: 98 }, { team: "25학번", score: 91 }], mapCaption: "대운동장 하단 부스 구역 오른쪽입니다." },
    { id: "food", name: "푸드트럭", location: "대운동장 상단 간식차 구역", start: "13:20", end: "16:35", summary: "닭꼬치, 회오리감자, 소시지, 타코야끼, 음료", guide: "2열 줄서기 유지, 쓰레기는 지정 수거함에 정리합니다.", mapCaption: "관람석 쪽 상단 라인에 푸드트럭이 줄지어 있습니다." },
  ],
  resultSports: [
    { id: "basketball", name: "농구", summary: "동점 시 자유투까지 기록", rounds: [{ name: "예선", matches: [{ label: "농구 예선 1", left: "23학번", right: "25학번", score: "38 : 38", extra: "자유투 3 : 2", winner: "23학번" }, { label: "농구 예선 2", left: "22학번", right: "26학번", score: "41 : 36", winner: "22학번" }] }] },
    { id: "futsal", name: "풋살", summary: "동점 시 승부차기 기록", rounds: [{ name: "예선", matches: [{ label: "풋살 예선 1", left: "24학번", right: "26학번", score: "1 : 1", extra: "승부차기 4 : 3", winner: "24학번" }, { label: "풋살 예선 2", left: "22학번", right: "23학번", score: "2 : 0", winner: "22학번" }] }] },
    { id: "rope", name: "줄다리기", summary: "3판 2선승제 · 세트 시간 기준 비교", rounds: [{ name: "예선", matches: [{ label: "줄다리기 예선 1", left: "25학번", right: "26학번", score: "2 : 0", extra: "세트 시간 38초 / 41초", winner: "25학번" }, { label: "줄다리기 예선 2", left: "22학번", right: "24학번", score: "2 : 1", extra: "세트 시간 45초 / 39초 / 48초", winner: "22학번" }] }] },
    { id: "relay", name: "계주", summary: "전체 학번 동시 경기 · 순위형 입력", rounds: [{ name: "최종 순위", matches: [{ label: "1위", left: "22학번", right: "1분 24초 12", score: "", winner: "" }, { label: "2위", left: "24학번", right: "1분 24초 88", score: "", winner: "" }] }] },
  ],
  rankings: [
    { team: "22학번", score: 31 },
    { team: "24학번", score: 28 },
    { team: "25학번", score: 24 },
    { team: "23학번", score: 22 },
    { team: "26학번", score: 19 },
  ],
  adminProfiles: {
    super_admin: {
      title: "대표 운영진",
      subtitle: "전체 읽기 / 전체 쓰기 / 배정 관리",
      assignedGames: ["basketball-final", "women-dodgeball-final"],
      assignedBooths: ["food", "weight"],
    },
    operator_futsal: {
      title: "일반 운영진 · 풋살 담당",
      subtitle: "내 경기 입력 가능 / 전체 대시보드 읽기 가능",
      assignedGames: ["futsal-qual-1", "futsal-qual-2", "futsal-semi"],
      assignedBooths: [],
    },
    operator_semis: {
      title: "일반 운영진 · 부결승 담당",
      subtitle: "예선 결과 확인 후 부결승 입력",
      assignedGames: ["basketball-semi", "rope-semi"],
      assignedBooths: [],
    },
    operator_booth: {
      title: "일반 운영진 · 부스 담당",
      subtitle: "내 부스 입력 가능 / 전체 결과 읽기 가능",
      assignedGames: [],
      assignedBooths: ["weight", "shoe", "chase"],
    },
  },
};
