[build]
  command = "npm install && npm run build && cp admin.html admin.js styles.css data.js dist/"
  publish = "dist"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
